-- MySQL Script generated by MySQL Workbench
-- Thu Oct  3 18:10:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jobMatch
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jobMatch` ;

-- -----------------------------------------------------
-- Schema jobMatch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jobMatch` DEFAULT CHARACTER SET utf8 ;
USE `jobMatch` ;

-- -----------------------------------------------------
-- Table `jobMatch`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobMatch`.`task` ;

CREATE TABLE IF NOT EXISTS `jobMatch`.`task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(4095) NULL,
  `ajattelu_value` INT NULL,
  `fysiikka_value` INT NULL,
  `sosiaalisuus_value` INT NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobMatch`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobMatch`.`question` ;

CREATE TABLE IF NOT EXISTS `jobMatch`.`question` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `min_value_desc` VARCHAR(255) NULL,
  `max_value_desc` VARCHAR(255) NULL,
  PRIMARY KEY (`question_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobMatch`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobMatch`.`image` ;

CREATE TABLE IF NOT EXISTS `jobMatch`.`image` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`image_id`),
  FOREIGN KEY (`task_id`)
    REFERENCES `jobMatch`.`task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
